### ISSUE TITLE
improve ux for web wallet vs random address field

### ISSUE THREAD

**Issue by nicolasochem** [avysel/tezos-testnet-faucet#3]
There are 2 ways to use the faucet. 1. use the web wallet. 2. enter address in a field

These 2 flows should be separate UI boxes. Right now it's confusing: I connect the wallet, but the button is under the field.

There should be another button when the wallet is connected "send tez to web wallet"

**Comment by avysel** [comment]
@nicolasochem what do you think about something like that:
(it may need a littte more work to make it more beautiful, but at least you can see page layout)

![image](https://user-images.githubusercontent.com/6792533/163383935-c3ecd59e-2da7-40d3-8c63-6deae0b1f749.png)

By the way, according to your experience with the Tezos ecosystem, do you really think that faucet with wallet address input form is that usefull ?

For example, for Ethereum, the Metamask faucet (https://faucet.metamask.io/) only works with connected wallet.

Another question:
Do you this it's useful to provide faucet for previous testnets, like Hangzhounet?
Maybe focus only on current mainnet protocol (Ithacanet) and protocol to come (the "J" one when it'll be released)

**Comment by nicolasochem** [comment]
thanks, I will try to deploy your faucet for jakartanet which is coming our shortly
