### ISSUE TITLE
don't hardcode `ithacanet`

### ISSUE THREAD

**Issue by nicolasochem** [avysel/tezos-testnet-faucet#9]
Hi, I'd like to deploy your faucet for jakarta testnet on the teztnets platform.

We would deploy on kubernetes, which means I need to create a config.json with parameters from the infra.

But I see in app.tsx that `ithacanet` is hardcoded everywhere: https://github.com/avysel/tezos-testnet-faucet/blob/main/src/App.tsx#L45

I would like to generate a [config.json](https://github.com/avysel/tezos-testnet-faucet/blob/main/src/config/config.json) with arbitrary network names, like jakartanet.

**Comment by avysel** [comment]
I'm not familiar with kubernetes, I'll need to get some information on it to be able to do it cleanly.

**Comment by nicolasochem** [comment]
You don't really need kubernetes familiarity, all that's required is that if I change `ithacanet` with `jakartanet` in the config, it should work.
But, once the docker build works, I should be able to point you to a minikube config to launch your faucet together with a private chain.
